version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        networks:
            - app-network

    php-fpm:
        image: php:8.2-fpm-alpine
        volumes:
            - .:/app
        networks:
            - app-network

    nginx:
        image: nginx:latest
        volumes:
            - .:/app
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        depends_on:
            - php-fpm
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
